### ISSUE TITLE
Historia de usuario: HU_08  Rol. Como usuario

### ISSUE THREAD

**Issue by RositaTorres** [RositaTorres/Desarrollo-movil-#18]
**Historia de usuario: HU_08**

Rol. Como usuario

Funcionalidad: deseo ver la ubicación del POI en Google Maps

Razón: para localizar el sitio en un mapa

**Comment by RositaTorres** [comment]
6. Criterios de evaluación y evidencia

Para la evaluación del sprint se deben lograr los criterios de aceptación de cada historia de usuario a trabajar:

Criterios de Aceptación HU_08

- [x] La ubicación debe lanzar una página que permita visualizar el lugar en el mapa de Google Maps o algún otro mapa OpenSource.

- [x]  Verificar de forma manual que no se presenten fallas en la aplicación

**Comment by SebastianGamez** [comment]
Listos!
